/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 carTwo.gltf --transform 
Files: carTwo.gltf [15.19MB] > C:\Users\USER\Downloads\mersedes-benz_s-class_w221\carTwo-transformed.glb [2.18MB] (86%)
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mersedes-benz-s-class-w221-6b1c0ad55406406a8cf8177dc0a4f2b9
Title: Mersedes-Benz S-class W221
*/

import { useGLTF } from '@react-three/drei';

export default function CarTwo(props) {
  const { nodes, materials } = useGLTF('/carTwo-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.sw221_headlight_L_fl_sw221_0.geometry}
        material={materials.sw221}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_headlight_L_fl_sw221_b_0.geometry}
        material={materials.sw221_b}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_headlight_L_fl_sw221_lights_lod0_0.geometry}
        material={materials.sw221_lights_lod0}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_headlight_L_fl_sw221_lights_lod0_2_0.geometry}
        material={materials.sw221_lights_lod0_2}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_headlight_L_fl_sw221_runninglight_fl_0.geometry}
        material={materials.sw221_runninglight_fl}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_headlight_L_fl_sw221_glass_0.geometry}
        material={materials.PaletteMaterial001}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_headlight_L_fl_sw221_interior_hl_0.geometry}
        material={materials.PaletteMaterial002}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_tubs_sw221_main_0.geometry}
        material={materials.PaletteMaterial002}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.sw221_taillight_R_fl_sw221_reverselight_fl_0.geometry}
        material={materials.sw221_reverselight_fl}
        position={[0.053, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_tailgate_sedan_sw221_nodamage_lod0_0.geometry}
        material={materials.sw221_nodamage_lod0}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_tailgate_sedan_sw221_interior_lod0_0.geometry}
        material={materials.sw221_interior_lod0}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_tailgate_sedan_sw221_paint_0.geometry}
        material={materials.PaletteMaterial003}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_tailgate_sedan_sw221_carpet_0.geometry}
        material={materials.sw221_carpet}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_sunvisor_sw221_alcantara_0.geometry}
        material={materials.sw221_alcantara}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_steer_sw221_badges_0.geometry}
        material={materials.sw221_badges}
        position={[0.421, 0.914, 0.159]}
        rotation={[-2.794, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_steer_sw221_interior_emissive_lod0_0.geometry}
        material={materials.sw221_interior_emissive_lod0}
        position={[0.421, 0.914, 0.159]}
        rotation={[-2.794, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_steer_sw221_wood_0.geometry}
        material={materials.sw221_wood}
        position={[0.421, 0.914, 0.159]}
        rotation={[-2.794, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_steer_sw221_leather2_0.geometry}
        material={materials.sw221_leather2}
        position={[0.421, 0.914, 0.159]}
        rotation={[-2.794, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_steer_sw221_stitching1_0.geometry}
        material={materials.sw221_stitching1}
        position={[0.421, 0.914, 0.159]}
        rotation={[-2.794, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_seats_R_sw221_belt_0.geometry}
        material={materials.sw221_belt}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_seats_R_sw221_perforated_0.geometry}
        material={materials.sw221_perforated}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_seats_R_sw221_alcantara1_b_0.geometry}
        material={materials.sw221_alcantara1_b}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_seats_R_sw221_leather1_0.geometry}
        material={materials.sw221_leather1}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_doorpanel_RR_sedan_sw221_harmankardon_0.geometry}
        material={materials.sw221_harmankardon}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_doorpanel_FR_sw221_harmankardon1_0.geometry}
        material={materials.sw221_harmankardon1}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_dash_sw221_screen_0.geometry}
        material={materials.sw221_screen}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_dash_sw221_screen_b_0.geometry}
        material={materials.sw221_screen_b}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_bumper_F_fl_amg_sw221_foglight_fl_0.geometry}
        material={materials.sw221_foglight_fl}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_seat_FR_sw221_dvd_0.geometry}
        material={materials.sw221_dvd}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.sw221_exhaust_R_sw221_0.geometry}
        material={materials.sw221}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.sw221_body_sedan_sw221_grill4_0.geometry}
        material={materials.sw221_grill4}
        position={[0.054, -0.036, -0.027]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/carTwo-transformed.glb');
