/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 carThree.gltf --transform 
Files: carThree.gltf [5.94MB] > C:\Users\USER\Downloads\2011_mercedes-benz_s_65_amg_w221\carThree-transformed.glb [1.28MB] (79%)
Author: supercarmodels (https://sketchfab.com/supercarmodels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2011-mercedes-benz-s-65-amg-w221-8ffa2d947cce478eb0a60cf1a230c592
Title: 2011 Mercedes-Benz S 65 AMG (W221)
*/

import { useGLTF } from '@react-three/drei';

export default function CarThree(props) {
  const { nodes, materials } = useGLTF('/carThree-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Meshesmiutubadging1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.Meshesmiutubay0011Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Meshesmiutubay0021Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.Meshesmiutubay0051Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.Meshesmiutubonnetok0051Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.Meshesmiutubootok0071Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials.Meshesmiutudigits0021Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.Meshesmiutudigits0031Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_19.geometry}
        material={materials.Meshesmiutudigits0041Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials.Meshesmiutudigits0081Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.Meshesmiutudigits0051Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials.Meshesmiutudigits0091Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.Meshesmiutudigits0071Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.Meshesmiutudoorlfok0081Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials.Meshesmiutudoorlfok0091Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_31.geometry}
        material={materials.Meshesmiutudoorlrok1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.Meshesmiutudoorrfok0081Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.Meshesmiutudoorrrok1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.Meshesmiutufara0021Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.Meshesmiutufrontglass1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_45.geometry}
        material={materials.Meshesmiutuinter0021Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.Meshesmiutuinter0091Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_47.geometry}
        material={materials.Meshesmiutuinter0111Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.Meshesmiutuinter0331Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_49.geometry}
        material={materials.Meshesmiutulrrearglass1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_51.geometry}
        material={materials.Meshesmiutulffrontglass1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_52.geometry}
        material={materials.Meshesmiuturearglass1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials.Meshesmiuturrrearglass1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_55.geometry}
        material={materials.Meshesmiutus65glass0011Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials.Meshesmiutus65glass0031Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_57.geometry}
        material={materials.Meshesmiutus65glass1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.Meshesmiutuseats1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_59.geometry}
        material={materials.Meshesmiutusteclo1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.Meshesmiutusteeringok1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_71.geometry}
        material={materials.Meshesmiutuunder1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_72.geometry}
        material={materials.Meshesmiutuw2210061Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials.Meshesmiutuw2210081Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_75.geometry}
        material={materials.Meshesmiutudoorlrok0021Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_79.geometry}
        material={materials.Meshesmiutudoorlrok0041Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_82.geometry}
        material={materials.Meshesmiutudoorrfok1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_94.geometry}
        material={materials.Meshesmiututlights1Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_95.geometry}
        material={materials.Meshesmiutuwheel0021Mtl}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/carThree-transformed.glb');
